seems to work

diff --git a/mysql_passwd b/mysql_passwd
--- a/mysql_passwd
+++ b/mysql_passwd
@@ -1,81 +1,72 @@
-#!/bin/bash
+#! /bin/bash
+#
+# Author: Bert Van Vreckem <bert.vanvreckem@gmail.com>
+#
+# A non-interactive replacement for mysql_secure_installation
+#
+# Tested on CentOS 6, CentOS 7, Ubuntu 12.04 LTS (Precise Pangolin), Ubuntu
+# 14.04 LTS (Trusty Tahr).
 
-#
-# Automate mysql secure installation for debian-baed systems
-# 
-#  - You can set a password for root accounts.
-#  - You can remove root accounts that are accessible from outside the local host.
-#  - You can remove anonymous-user accounts.
-#  - You can remove the test database (which by default can be accessed by all users, even anonymous users), 
-#    and privileges that permit anyone to access databases with names that start with test_. 
-#  For details see documentation: http://dev.mysql.com/doc/refman/5.7/en/mysql-secure-installation.html
-#
-# @version 13.08.2014 00:39 +03:00
-# Tested on Debian 7.6 (wheezy)
-#
-# Usage:
-#  Setup mysql root password:  ./mysql_secure.sh 'your_new_root_password'
-#  Change mysql root password: ./mysql_secure.sh 'your_old_root_password' 'your_new_root_password'"
-#
+set -o errexit # abort on nonzero exitstatus
+set -o nounset # abort on unbound variable
 
-# Delete package expect when script is done
-# 0 - No; 
-# 1 - Yes.
-#
-# Check the bash shell script is being run by root
-#
-if [[ $EUID -ne 0 ]]; then
-   echo "This script must be run as root" 1>&2
-   exit 1
+#{{{ Functions
+
+usage() {
+cat << _EOF_
+
+Usage: ${0} "ROOT PASSWORD"
+
+  with "ROOT PASSWORD" the desired password for the database root user.
+
+Use quotes if your password contains spaces or other special characters.
+_EOF_
+}
+
+# Predicate that returns exit status 0 if the database root password
+# is set, a nonzero exit status otherwise.
+is_mysql_root_password_set() {
+  ! mysqladmin --user=root status > /dev/null 2>&1
+}
+
+# Predicate that returns exit status 0 if the mysql(1) command is available,
+# nonzero exit status otherwise.
+is_mysql_command_available() {
+  which mysql > /dev/null 2>&1
+}
+
+#}}}
+#{{{ Command line parsing
+
+if [ "$#" -ne "1" ]; then
+  echo "Expected 1 argument, got $#" >&2
+  usage
+  exit 2
 fi
 
-#
-# Check input params
-#
-if [ -n "${1}" -a -z "${2}" ]; then
-    # Setup root password
-    CURRENT_MYSQL_PASSWORD=''
-    NEW_MYSQL_PASSWORD="${1}"
-elif [ -n "${1}" -a -n "${2}" ]; then
-    # Change existens root password
-    CURRENT_MYSQL_PASSWORD="${1}"
-    NEW_MYSQL_PASSWORD="${2}"
-else
-    echo "Usage:"
-    echo "  Setup mysql root password: ${0} 'your_new_root_password'"
-    echo "  Change mysql root password: ${0} 'your_old_root_password' 'your_new_root_password'"
-    exit 1
+#}}}
+#{{{ Variables
+db_root_password="${1}"
+#}}}
+
+# Script proper
+
+if ! is_mysql_command_available; then
+  echo "The MySQL/MariaDB client mysql(1) is not installed."
+  exit 1
 fi
 
-#
-# Check is expect package installed
-#
-if [ $(dpkg-query -W -f='${Status}' expect 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
-    echo "Can't find expect. Trying install it..."
-    apt -y install expect
-
+if is_mysql_root_password_set; then
+  echo "Database root password already set"
+  exit 0
 fi
 
-SECURE_MYSQL=$(expect -c "
-set timeout 3
-spawn mysql_secure_installation
-expect \"Enter current password for root (enter for none):\"
-send \"$CURRENT_MYSQL_PASSWORD\r\"
-expect \"root password?\"
-send \"y\r\"
-expect \"New password:\"
-send \"$NEW_MYSQL_PASSWORD\r\"
-expect \"Re-enter new password:\"
-send \"$NEW_MYSQL_PASSWORD\r\"
-expect \"Remove anonymous users?\"
-send \"y\r\"
-expect \"Disallow root login remotely?\"
-send \"y\r\"
-expect \"Remove test database and access to it?\"
-send \"y\r\"
-expect \"Reload privilege tables now?\"
-send \"y\r\"
-expect eof
-")
 
-exit 0
+mysql --user=root <<_EOF_
+  ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${db_root_password}';
+  DELETE FROM mysql.user WHERE User='';
+  DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
+  DROP DATABASE IF EXISTS test;
+  DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
+  FLUSH PRIVILEGES;
+_EOF_
